# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee760ba23d319233f2f8030070f81b0bfbaf4379bcb7a6a1e82d91ce4bbf10d479bd0280224ad1048cde94f577fe79814b98564915ba371d6d924477d694a72

test:
  secret_key_base: 38a6dbe5584389c47cccb3d66d3a6f6ea567fdb4ff3368c45933d9ab69acc528993d3a58dfdff029a5797399189222179f102e795a45d31d15ace5ba95fb0485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
